Frontend:
  impl: LoadStoreTrace
  clock_ratio: 1
  # path: ./perf_comparison/traces/random_5M_R8W2_ramulatorv2.trace
  # path: ./perf_comparison/traces/random_5M_R5W5_ramulatorv2.trace
  # path: ./perf_comparison/traces/random_5M_R2W8_ramulatorv2.trace
  path: ./perf_comparison/traces/stream_5M_R8W2_ramulatorv2.trace
  # path: ./perf_comparison/traces/stream_5M_R5W5_ramulatorv2.trace
  # path: ./perf_comparison/traces/stream_5M_R2W8_ramulatorv2.trace
  # path: memory_trace.txt
  Translation:
    impl: NoTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: ndpDRAM
  clock_ratio: 1

  DRAM:
    impl: DDR5-pCH
    org:
      # DBX Preset: DDR5_16Gb_x4, DDR5_16Gb_x8, DDR5_16Gb_x16 
      preset: DDR5_16Gb_x4
      channel: 2
      pseudochannel : 4
      rank: 1
      # DRAM DQs on DIMM-side: 4, 8, 16  
      dq: 4
      real_dq: 4
    timing:
      preset: DDR5_4800B 
    RFM:
      BRC: 0  
    drampower_enable: true
    power_debug: false
    use_db_fetch: true
    ndp_inst_slot: 8
    voltage:
      preset: Default
    current:
      # DBX preset: DDR5_4800x4, DDR5_4800x8, DDR5_4800x16
      preset: DDR5_4800x4

  Controller:
    impl: ndpDRAMCtrl
    Scheduler:
      impl: NDPFRFCFS
    RefreshManager:
      impl: DR5CHAllBank
    RowPolicy:
      impl: OpenRowPolicy
      # impl: ClosedRowPolicyPch
      cap: 4
    plugins:

  AddrMapper:
    # impl: RoRaCoBaPcCh
    # impl: RoRabkCoBgPcCh    
    # impl: RoBaRaCoPcCh
    impl: RoCoBaRaPcCh
    
